-- MySQL Script generated by MySQL Workbench
-- Thu Sep 26 12:08:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DA3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DA3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DA3` DEFAULT CHARACTER SET utf8 ;
USE `DA3` ;

DROP TABLE IF EXISTS `DA3`.`Electrovalvulas` ;
DROP TABLE IF EXISTS `DA3`.`Dispositivos` ;
DROP TABLE IF EXISTS `DA3`.`Mediciones` ;
DROP TABLE IF EXISTS `DA3`.`Log_Riegos` ;

-- -----------------------------------------------------
-- Table `DA3`.`Electrovalvulas`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `DA3`.`Electrovalvulas` (
  `electrovalvulaId` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`electrovalvulaId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DA3`.`Dispositivos`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `DA3`.`Dispositivos` (
  `dispositivoId` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL,
  `serial` VARCHAR(200) NOT NULL,
  `ubicacion` VARCHAR(200) NULL,
  `estado` BOOLEAN NOT NULL,
  `electrovalvulaId` INT NOT NULL,
  PRIMARY KEY (`dispositivoId`, `electrovalvulaId`),
  INDEX `fk_Dispositivos_Electrovalvulas1_idx` (`electrovalvulaId` ASC) ,
  CONSTRAINT `fk_Dispositivos_Electrovalvulas1`
    FOREIGN KEY (`electrovalvulaId`)
    REFERENCES `DA3`.`Electrovalvulas` (`electrovalvulaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DA3`.`Mediciones`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `DA3`.`Mediciones` (
  `medicionId` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `humedad` FLOAT NULL,
  `temperatura` FLOAT NULL,
  `dispositivoId` INT NOT NULL,
  PRIMARY KEY (`medicionId`, `dispositivoId`),
  INDEX `fk_Mediciones_Dispositivos_idx` (`dispositivoId` ASC) ,
  CONSTRAINT `fk_Mediciones_Dispositivos`
    FOREIGN KEY (`dispositivoId`)
    REFERENCES `DA3`.`Dispositivos` (`dispositivoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DA3`.`Log_Riegos`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `DA3`.`Log_Riegos` (
  `logRiegoId` INT NOT NULL AUTO_INCREMENT,
  `apertura` TINYINT NULL,
  `fecha` DATETIME NULL,
  `electrovalvulaId` INT NOT NULL,
  PRIMARY KEY (`logRiegoId`, `electrovalvulaId`),
  INDEX `fk_Log_Riegos_Electrovalvulas1_idx` (`electrovalvulaId` ASC) ,
  CONSTRAINT `fk_Log_Riegos_Electrovalvulas1`
    FOREIGN KEY (`electrovalvulaId`)
    REFERENCES `DA3`.`Electrovalvulas` (`electrovalvulaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- INSERT INTO DA3.Electrovalvulas (nombre) VALUES ('eLPatio');
-- INSERT INTO DA3.Electrovalvulas (nombre) VALUES ('eLCocina');
-- INSERT INTO DA3.Electrovalvulas (nombre) VALUES ('eLJardinDelantero');
-- INSERT INTO DA3.Electrovalvulas (nombre) VALUES ('eLLiving');
-- INSERT INTO DA3.Electrovalvulas (nombre) VALUES ('eLHabitacion1');
-- INSERT INTO DA3.Electrovalvulas (nombre) VALUES ('eLHabitacion2');


-- INSERT INTO DA3.Dispositivos (nombre,ubicacion,electrovalvulaId) VALUES ('Sensor 1', 'Patio',1);
-- INSERT INTO DA3.Dispositivos (nombre,ubicacion,electrovalvulaId) VALUES ('Sensor 2', 'Cocina',2);
-- INSERT INTO DA3.Dispositivos (nombre,ubicacion,electrovalvulaId) VALUES ('Sensor 3', 'Jardin Delantero',3);
-- INSERT INTO DA3.Dispositivos (nombre,ubicacion,electrovalvulaId) VALUES ('Sensor 4', 'Living',4);
-- INSERT INTO DA3.Dispositivos (nombre,ubicacion,electrovalvulaId) VALUES ('Sensor 5', 'Habitacion 1',5);
-- INSERT INTO DA3.Dispositivos (nombre,ubicacion,electrovalvulaId) VALUES ('Sensor 6', 'Habitacion 2',6);


-- INSERT INTO DA3.Mediciones (fecha,valor,dispositivoId) VALUES (current_timestamp(),60,1 );
-- INSERT INTO DA3.Mediciones (fecha,valor,dispositivoId) VALUES (current_timestamp(),40,1 );
-- INSERT INTO DA3.Mediciones (fecha,valor,dispositivoId) VALUES (current_timestamp(),30,2 );
-- INSERT INTO DA3.Mediciones (fecha,valor,dispositivoId) VALUES (current_timestamp(),50,3 );VARCHAR(100)
-- INSERT INTO DA3.Mediciones (fecha,valor,dispositivoId) VALUES (current_timestamp(),33,5 );
-- INSERT INTO DA3.Mediciones (fecha,valor,dispositivoId) VALUES (current_timestamp(),17,4 );
-- INSERT INTO DA3.Mediciones (fecha,valor,dispositivoId) VALUES (current_timestamp(),29,6 );
-- INSERT INTO DA3.Mediciones (fecha,valor,dispositivoId) VALUES (current_timestamp(),20,1 );
-- INSERT INTO DA3.Mediciones (fecha,valor,dispositivoId) VALUES (current_timestamp(),44,4 );
-- INSERT INTO DA3.Mediciones (fecha,valor,dispositivoId) VALUES (current_timestamp(),61,5 );
-- INSERT INTO DA3.Mediciones (fecha,valor,dispositivoId) VALUES (current_timestamp(),12,2 );


-- INSERT INTO DA3.Log_Riegos (apertura,fecha,electrovalvulaId) VALUES (0,current_timestamp(),1 );
-- INSERT INTO DA3.Log_Riegos (apertura,fecha,electrovalvulaId) VALUES (0,current_timestamp(),2 );
-- INSERT INTO DA3.Log_Riegos (apertura,fecha,electrovalvulaId) VALUES (0,current_timestamp(),3 );
-- INSERT INTO DA3.Log_Riegos (apertura,fecha,electrovalvulaId) VALUES (0,current_timestamp(),4 );
-- INSERT INTO DA3.Log_Riegos (apertura,fecha,electrovalvulaId) VALUES (0,current_timestamp(),5 );
-- INSERT INTO DA3.Log_Riegos (apertura,fecha,electrovalvulaId) VALUES (0,current_timestamp(),6 );

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;